services:
  db:
    image: postgres:17  
    restart: always
    environment:
      POSTGRES_USER: smsuser
      POSTGRES_PASSWORD: smspassword
      POSTGRES_DB: smsprocessor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sms_network

  backend:
    image: chiramlittleton/smsprocessor-backend:latest  
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: smsuser
      DB_PASS: smspassword
      DB_NAME: smsprocessor
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/usr/src/app  
    command: ["node", "/usr/src/app/src/server.js"]
    networks:
      - sms_network

  frontend:
    image: chiramlittleton/smsprocessor-frontend:latest  
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - sms_network

volumes:
  pgdata:

networks:
  sms_network:
    driver: bridge
