name: Build, Test, and Push Docker Image (macOS ARM64)

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest #keep ubuntu, arm64 builds fine on ubuntu.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64 # build only arm64

      - name: Build Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          tags: smsprocessor-backend:test
          platforms: linux/arm64

      - name: Run Backend Tests in Docker Container
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          tags: smsprocessor-backend:test-amd64 #change the test tag.
          platforms: linux/amd64 #build the test image as an amd64 image.

      - name: Run Backend Tests in Docker Container
        run: |
          docker run --rm smsprocessor-backend:test-amd64 npx jest --coverage

      - name: Build Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          tags: smsprocessor-frontend:test
          platforms: linux/arm64

      - name: Push Backend Docker Image (Only if tests pass)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smsprocessor:latest #Changed tag
          platforms: linux/arm64

      - name: Push Frontend Docker Image (Only if tests pass)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smsprocessor-frontend:latest
          platforms: linux/arm64